-- liquibase formatted sql

-- changeset root:1722902057282-1
CREATE TABLE "accountcurrencies" ("account_id" INTEGER NOT NULL, "currency_id" INTEGER NOT NULL, CONSTRAINT "accountcurrencies_pkey" PRIMARY KEY ("account_id", "currency_id"));

-- changeset root:1722902057282-2
CREATE TABLE "accounts" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" TEXT NOT NULL, "initial_amount" INTEGER NOT NULL, CONSTRAINT "accounts_pkey" PRIMARY KEY ("id"));

-- changeset root:1722902057282-3
CREATE TABLE "categories" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" TEXT NOT NULL, "parent" INTEGER, "icon_name" TEXT NOT NULL, CONSTRAINT "categories_pkey" PRIMARY KEY ("id"));

-- changeset root:1722902057282-4
CREATE TABLE "currencies" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" TEXT NOT NULL, "symbol" TEXT NOT NULL, CONSTRAINT "currencies_pkey" PRIMARY KEY ("id"));

-- changeset root:1722902057282-5
CREATE TABLE "transactions" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "amount" INTEGER NOT NULL, "currency" INTEGER NOT NULL, "sender" INTEGER, "receiver" INTEGER, "category" INTEGER NOT NULL, "date" date NOT NULL, "note" TEXT, CONSTRAINT "transactions_pkey" PRIMARY KEY ("id"));

-- changeset root:1722902057282-6
ALTER TABLE "accountcurrencies" ADD CONSTRAINT "accountcurrencies_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "accounts" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset root:1722902057282-7
ALTER TABLE "accountcurrencies" ADD CONSTRAINT "accountcurrencies_currency_id_fkey" FOREIGN KEY ("currency_id") REFERENCES "currencies" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset root:1722902057282-8
ALTER TABLE "categories" ADD CONSTRAINT "categories_parent_fkey" FOREIGN KEY ("parent") REFERENCES "categories" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset root:1722902057282-9
ALTER TABLE "transactions" ADD CONSTRAINT "transactions_category_fkey" FOREIGN KEY ("category") REFERENCES "categories" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset root:1722902057282-10
ALTER TABLE "transactions" ADD CONSTRAINT "transactions_currency_fkey" FOREIGN KEY ("currency") REFERENCES "currencies" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset root:1722902057282-11
ALTER TABLE "transactions" ADD CONSTRAINT "transactions_receiver_fkey" FOREIGN KEY ("receiver") REFERENCES "accounts" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset root:1722902057282-12
ALTER TABLE "transactions" ADD CONSTRAINT "transactions_sender_fkey" FOREIGN KEY ("sender") REFERENCES "accounts" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

